theme: minima
title: Sharing Documentaion
author: Lynn Hendricks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Not sure if we want to use this feature, it is public and google searchable.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
